name: JulySafe
author: July_ss
version: 1.0.1
main: com.github.julyss2019.bukkit.plugins.julysafe.JulySafe
api-version: 1.13
softdepend:
  - JulyLibrary
commands:
  julysafe:
    aliases:
      - jsafe
